name: Pull Request

on: 
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: files-present-action
      uses: JJ/files-present-action@releases/v1
      with:
        # Array describing the files
        files: | #"README.md, .prettierrc.js, .eslintrc.js, .gitignore, package.json, LICENSE, THIRD_PARTY_NOTICES.md, CODE_OF_CONDUCT.md, cla.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/enhancement.md, nr1.json, catalog/config.json"
          README.md
          ,.prettierrc.js
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Dependencies
      run: npm install
    - name: Install NR1 CLI
      run: curl -s https://cli.nr-ext.net/installer.sh | sudo bash
    - name: NR1 Nerdpack Build
      run: nr1 nerdpack:build
    - name: ESLinting
      run: npm run eslint-check
    - name: Test Code
      run: npm test
