name: CI

on: 
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    
    # Checkout base repo
    - name: Checkout
      uses: actions/checkout@v2
    
    
    # List contents of repo
    - name: List directory
      run:  ls -la
      
    # This would checkout all the submodules, even though we only need the one for _this_ PR
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
    
    # List contents of repo
    - name: List directory
      run:  ls -la
            
    # This would checkout submodule `foo` (if we can get foo...)
    #- uses: Mushus/checkout-submodule@v1
    #  with:
    #    submodulePath: ./foo
    
    - name: files-present-action
      uses: JJ/files-present-action@releases/v1
      with:
        # Array describing the files
        files: "README.md, .prettierrc.js, .eslintrc.js, .gitignore, package.json, LICENSE, THIRD_PARTY_NOTICES.md, CODE_OF_CONDUCT.md, cla.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/enhancement.md, nr1.json, catalog/config.json"
    
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    
    - name: Install Dependencies
      run: npm install
    
    - name: Install NR1 CLI
      run: curl -s https://cli.nr-ext.net/installer.sh | sudo bash
    
    - name: NR1 Nerdpack Build
      run: nr1 nerdpack:build
    
    # Validate Ability to publish code (Issue #2)
    # Requires API key
    #- name: NR1 Nerdpack Build
    #  run: nr1 nerdpack:publish --dry-run
    
    #- name: Publish and deploy Nerdpack
    #  env:
    #    NR1_API_KEY: ${{ secrets.DEMOTRON_V2_API_KEY }}
    #    NR1_REGION: us
    #  run: |
    #    nr1 profiles:add --name workflow --api-key "$NR1_API_KEY" --region "$NR1_REGION" &&
    #    nr1 nerdpack:publish --dry-run

#        nr1 nerdpack:publish --profile=workflow &&
#        nr1 nerdpack:deploy --channel="$NR1_DEPLOY_CHANNEL"
    
    - name: ESLinting
      run: npm run eslint-check
    
    - name: Test Code
      run: npm test
